-- Generated by scripts/generate-seed-sql.mts — edit lib/data/seed-data.ts instead.

insert into campuses (id, slug, name, city, timezone) values
  ('c0000000-0000-4000-8000-000000000001', 'demo', 'Demo University', 'Sample data', 'America/Chicago')
on conflict (id) do nothing;

insert into tags (slug, label, category) values
  ('freshmen', 'Freshmen', 'audience'),
  ('upperclassmen', 'Upperclassmen', 'audience'),
  ('grad-students', 'Grad students', 'audience'),
  ('men', 'Men', 'audience'),
  ('women', 'Women', 'audience'),
  ('co-ed', 'Everyone', 'audience'),
  ('book-study', 'Book of the Bible', 'topic'),
  ('topical', 'Topical', 'topic'),
  ('prayer', 'Prayer', 'topic'),
  ('new-to-faith', 'New to faith', 'topic')
on conflict (slug) do nothing;

insert into leaders (id, name, photo_url, bio, public_phone, whatsapp, approved) values
  ('0b1f3c1e-1111-4a00-8000-000000000001', 'Maria Delgado', null, 'Mom of three, nurse by day, and the person who always has an extra chair. I''ve led this group for six years and love watching people find their people.', '+15125550101', true, true),
  ('0b1f3c1e-1111-4a00-8000-000000000002', 'James Okafor', null, 'Grad student in civil engineering. I started asking big questions in college and still am — bring yours.', '+15125550102', false, true),
  ('0b1f3c1e-1111-4a00-8000-000000000003', 'Priya Nair', null, 'Software designer and early riser. Coffee is on me; the questions are on you.', null, false, true),
  ('0b1f3c1e-1111-4a00-8000-000000000004', 'Tom Becker', null, 'Retired high-school history teacher. Married 41 years to Ruth, who co-leads with me and keeps me on time.', '+15125550104', false, true),
  ('0b1f3c1e-1111-4a00-8000-000000000005', 'Ruth Becker', null, 'Gardener, grandmother, and resident pie baker.', null, false, true),
  ('0b1f3c1e-1111-4a00-8000-000000000006', 'Andre Wallace', null, 'Contractor and dad. Our group is honest, low-key, and done by 7:30 so everyone gets to work.', '+15125550106', true, true),
  ('0b1f3c1e-1111-4a00-8000-000000000007', 'Hannah Kim', null, 'I moved here knowing no one. This group is the thing I wish I''d found sooner.', '+15125550107', true, true)
on conflict (id) do nothing;

insert into bible_studies (id, campus_id, slug, title, summary, description, curriculum, day_of_week, start_time, duration_minutes, timezone, cadence, anchor_date, format, neighborhood, location_name, food, capacity) values
  ('5a7d0c2e-2222-4b00-8000-000000000001', 'c0000000-0000-4000-8000-000000000001', 'tuesday-night-in-mark', 'Tuesday Night in Mark', 'A relaxed walk through Mark''s Gospel over a home-cooked dinner.', 'We eat first (around 6:30), then open the Bible together around 7. No prep, no homework, and no one will put you on the spot to read aloud or pray. Just show up hungry.', 'The Gospel of Mark', 2, '18:30', 120, 'America/Chicago', 'weekly', '2026-09-01', 'in_person', 'Eastwood', 'The Delgado home', 'meal', 16),
  ('5a7d0c2e-2222-4b00-8000-000000000002', 'c0000000-0000-4000-8000-000000000001', 'campus-questions', 'Campus Questions', 'Skeptics welcome. Big questions, honest conversation, free pizza.', 'Each week we take one question people actually ask (Is the Bible reliable? Why is there suffering?) and read what Scripture says. Believers, doubters, and the just-curious all fit here.', 'Topical — a new question every week', 3, '19:30', 75, 'America/Chicago', 'weekly', '2026-09-02', 'in_person', 'University District', 'Student Union, Room 214', 'meal', null),
  ('5a7d0c2e-2222-4b00-8000-000000000003', 'c0000000-0000-4000-8000-000000000001', 'sunrise-psalms', 'Sunrise Psalms', 'Thirty minutes in the Psalms before work. Cameras optional.', 'One psalm, a few minutes of quiet, a short conversation, and a closing prayer. We start and end on time. Join from your kitchen in your pajamas — nobody minds.', 'The Psalms', 4, '06:30', 30, 'America/Chicago', 'weekly', '2026-09-03', 'online', null, 'Zoom', 'none', null),
  ('5a7d0c2e-2222-4b00-8000-000000000004', 'c0000000-0000-4000-8000-000000000001', 'saturday-mens-breakfast', 'Saturday Men''s Breakfast', 'Eggs, coffee, and James — the most practical book in the Bible.', 'Tables of six to eight guys. We read a short passage, talk about where it hits real life, and pray for each other. Done by 7:30 so you still have your Saturday.', 'The Letter of James', 6, '06:30', 60, 'America/Chicago', 'weekly', '2026-09-05', 'in_person', 'Northside', 'Blue Door Diner (back room)', 'meal', 24),
  ('5a7d0c2e-2222-4b00-8000-000000000005', 'c0000000-0000-4000-8000-000000000001', 'women-of-the-word', 'Women of the Word', 'Women reading Ruth together, with coffee and plenty of grace.', 'A warm, mixed-age group of women. We read a chapter aloud, talk through three questions, and share prayer requests.', 'Ruth', 3, '09:30', 90, 'America/Chicago', 'weekly', '2026-09-02', 'hybrid', 'Riverside', 'Riverside Community Church, Fellowship Hall', 'snacks', 20),
  ('5a7d0c2e-2222-4b00-8000-000000000006', 'c0000000-0000-4000-8000-000000000001', 'twenty-somethings', 'Twenty-Somethings', 'New in town? Start here. Young adults, board games after.', 'We read through Acts and talk about what community looked like for the early church — then we try to actually do it. Stick around after for games and late-night tacos.', 'Acts', 0, '19:00', 90, 'America/Chicago', 'weekly', '2026-09-06', 'in_person', 'Downtown', 'Hannah''s apartment', 'snacks', 14),
  ('5a7d0c2e-2222-4b00-8000-000000000007', 'c0000000-0000-4000-8000-000000000001', 'golden-years-genesis', 'Golden Years in Genesis', 'Unhurried afternoon study for retirees. Pie every week.', 'We move slowly and enjoy it. Large-print Bibles on hand, plenty of parking, and no stairs. Ruth''s pie is not optional.', 'Genesis', 1, '14:00', 90, 'America/Chicago', 'biweekly', '2026-09-14', 'in_person', 'Northside', 'The Becker home', 'snacks', 12),
  ('5a7d0c2e-2222-4b00-8000-000000000008', 'c0000000-0000-4000-8000-000000000001', 'couples-on-mission', 'Couples on Mission', 'Married or engaged? Dinner, date-night energy, and Ephesians.', 'Every other Friday. Couples take turns hosting a potluck, then we split into men''s and women''s circles for the second half. Babysitting co-op available.', 'Ephesians', 5, '18:30', 150, 'America/Chicago', 'biweekly', '2026-09-11', 'in_person', 'Eastwood', 'Rotating homes', 'meal', 10),
  ('5a7d0c2e-2222-4b00-8000-000000000009', 'c0000000-0000-4000-8000-000000000001', 'lunch-break-prayer', 'Lunch-Break Prayer', 'Twenty-five minutes of Scripture and prayer from your desk.', 'A short reading, a few shared requests, and we pray. Built for people who can''t make evenings. Drop in any week — no need to come every time.', 'Daily lectionary reading', 2, '12:05', 25, 'America/Chicago', 'weekly', '2026-09-01', 'online', null, 'Google Meet', 'none', null)
on conflict (id) do nothing;

insert into campus_contacts (campus_id, leader_id, sort_order) values
  ('c0000000-0000-4000-8000-000000000001', '0b1f3c1e-1111-4a00-8000-000000000007', 0)
on conflict (campus_id, leader_id) do nothing;

update study_private set address = '4108 Pecan Grove Ln, Eastwood', meeting_url = null where study_id = '5a7d0c2e-2222-4b00-8000-000000000001';

update study_private set address = 'Student Union Room 214, 2308 Whitis Ave', meeting_url = null where study_id = '5a7d0c2e-2222-4b00-8000-000000000002';

update study_private set address = null, meeting_url = 'https://zoom.us/j/0000000000' where study_id = '5a7d0c2e-2222-4b00-8000-000000000003';

update study_private set address = '911 N Lamar Blvd', meeting_url = null where study_id = '5a7d0c2e-2222-4b00-8000-000000000004';

update study_private set address = '1200 Riverside Dr', meeting_url = 'https://meet.google.com/aaa-bbbb-ccc' where study_id = '5a7d0c2e-2222-4b00-8000-000000000005';

update study_private set address = '300 Congress Ave, Apt 1204', meeting_url = null where study_id = '5a7d0c2e-2222-4b00-8000-000000000006';

update study_private set address = '7702 Shoal Creek Blvd', meeting_url = null where study_id = '5a7d0c2e-2222-4b00-8000-000000000007';

update study_private set address = 'Sent by text each week', meeting_url = null where study_id = '5a7d0c2e-2222-4b00-8000-000000000008';

update study_private set address = null, meeting_url = 'https://meet.google.com/xxx-yyyy-zzz' where study_id = '5a7d0c2e-2222-4b00-8000-000000000009';

insert into study_leaders (study_id, leader_id, role, sort_order) values
  ('5a7d0c2e-2222-4b00-8000-000000000001', '0b1f3c1e-1111-4a00-8000-000000000001', 'leader', 0),
  ('5a7d0c2e-2222-4b00-8000-000000000002', '0b1f3c1e-1111-4a00-8000-000000000002', 'leader', 0),
  ('5a7d0c2e-2222-4b00-8000-000000000003', '0b1f3c1e-1111-4a00-8000-000000000003', 'leader', 0),
  ('5a7d0c2e-2222-4b00-8000-000000000004', '0b1f3c1e-1111-4a00-8000-000000000006', 'leader', 0),
  ('5a7d0c2e-2222-4b00-8000-000000000005', '0b1f3c1e-1111-4a00-8000-000000000007', 'leader', 0),
  ('5a7d0c2e-2222-4b00-8000-000000000006', '0b1f3c1e-1111-4a00-8000-000000000007', 'leader', 0),
  ('5a7d0c2e-2222-4b00-8000-000000000007', '0b1f3c1e-1111-4a00-8000-000000000004', 'leader', 0),
  ('5a7d0c2e-2222-4b00-8000-000000000007', '0b1f3c1e-1111-4a00-8000-000000000005', 'co_leader', 1),
  ('5a7d0c2e-2222-4b00-8000-000000000008', '0b1f3c1e-1111-4a00-8000-000000000001', 'leader', 0),
  ('5a7d0c2e-2222-4b00-8000-000000000009', '0b1f3c1e-1111-4a00-8000-000000000003', 'leader', 0)
on conflict (study_id, leader_id) do nothing;

insert into study_tags (study_id, tag_id)
  select '5a7d0c2e-2222-4b00-8000-000000000001', id from tags where slug in ('co-ed', 'book-study')
on conflict do nothing;

insert into study_tags (study_id, tag_id)
  select '5a7d0c2e-2222-4b00-8000-000000000002', id from tags where slug in ('freshmen', 'topical', 'new-to-faith')
on conflict do nothing;

insert into study_tags (study_id, tag_id)
  select '5a7d0c2e-2222-4b00-8000-000000000003', id from tags where slug in ('co-ed', 'upperclassmen', 'prayer')
on conflict do nothing;

insert into study_tags (study_id, tag_id)
  select '5a7d0c2e-2222-4b00-8000-000000000004', id from tags where slug in ('men', 'book-study')
on conflict do nothing;

insert into study_tags (study_id, tag_id)
  select '5a7d0c2e-2222-4b00-8000-000000000005', id from tags where slug in ('women', 'book-study')
on conflict do nothing;

insert into study_tags (study_id, tag_id)
  select '5a7d0c2e-2222-4b00-8000-000000000006', id from tags where slug in ('upperclassmen', 'co-ed', 'book-study')
on conflict do nothing;

insert into study_tags (study_id, tag_id)
  select '5a7d0c2e-2222-4b00-8000-000000000007', id from tags where slug in ('grad-students', 'co-ed', 'book-study')
on conflict do nothing;

insert into study_tags (study_id, tag_id)
  select '5a7d0c2e-2222-4b00-8000-000000000008', id from tags where slug in ('topical')
on conflict do nothing;

insert into study_tags (study_id, tag_id)
  select '5a7d0c2e-2222-4b00-8000-000000000009', id from tags where slug in ('co-ed', 'prayer')
on conflict do nothing;
