// Compiles lib/data/seed-data.ts into supabase/seed.sql.
// Run with: npm run db:seed-sql   (Node 22.18+ strips the types natively)
import { writeFileSync } from "node:fs";
import { seedLeaders, seedStudies, seedTags } from "../lib/data/seed-data.ts";

type Value = string | number | boolean | null;

const lit = (v: Value) =>
  v === null ? "null" : typeof v === "string" ? `'${v.replaceAll("'", "''")}'` : String(v);

function insert(table: string, rows: Record<string, Value>[], conflict: string) {
  const cols = Object.keys(rows[0]);
  const values = rows.map((r) => `  (${cols.map((c) => lit(r[c])).join(", ")})`).join(",\n");
  return `insert into ${table} (${cols.join(", ")}) values\n${values}\non conflict ${conflict} do nothing;\n`;
}

const sql = [
  "-- Generated by scripts/generate-seed-sql.mts — edit lib/data/seed-data.ts instead.\n",
  insert(
    "tags",
    seedTags.map((t) => ({ slug: t.slug, label: t.label, category: t.category })),
    "(slug)",
  ),
  insert(
    "leaders",
    seedLeaders.map((l) => ({
      id: l.id,
      name: l.name,
      photo_url: l.photoUrl,
      bio: l.bio,
      email: l.email,
      public_phone: l.publicPhone,
      whatsapp: l.whatsapp,
    })),
    "(id)",
  ),
  insert(
    "bible_studies",
    seedStudies.map((s) => ({
      id: s.id,
      slug: s.slug,
      title: s.title,
      summary: s.summary,
      description: s.description,
      curriculum: s.curriculum,
      day_of_week: s.dayOfWeek,
      start_time: s.startTime,
      duration_minutes: s.durationMinutes,
      timezone: s.timezone,
      cadence: s.cadence,
      anchor_date: s.anchorDate,
      format: s.format,
      neighborhood: s.neighborhood,
      location_name: s.locationName,
      address: s.address,
      meeting_url: s.meetingUrl,
      childcare: s.childcare,
      food: s.food,
      capacity: s.capacity,
    })),
    "(id)",
  ),
  insert(
    "study_leaders",
    seedStudies.flatMap((s) =>
      s.leaderIds.map((leaderId, i) => ({
        study_id: s.id,
        leader_id: leaderId,
        role: i === 0 ? "leader" : "co_leader",
        sort_order: i,
      })),
    ),
    "(study_id, leader_id)",
  ),
  ...seedStudies.map(
    (s) =>
      `insert into study_tags (study_id, tag_id)\n  select ${lit(s.id)}, id from tags where slug in (${s.tagSlugs.map(lit).join(", ")})\non conflict do nothing;\n`,
  ),
].join("\n");

writeFileSync(new URL("../supabase/seed.sql", import.meta.url), sql);
console.log("Wrote supabase/seed.sql");
